name: Build and test
on:
  push:
    branches:
    - master
    - test
jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
        - Debug
        - Release
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Update packages
      run: sudo apt update --quiet -y
    - name: Install build dependencies for Premake
      run: sudo apt install --quiet -y uuid-dev
    - name: Run test workflow
      run: ./scripts/tests/workflow.sh
  macosx:
    runs-on: macos-latest
    strategy:
      matrix:
        config:
        - Debug
        - Release
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Run test workflow
      run: ./scripts/tests/workflow.sh
